---

# based on https://github.com/hpcng/warewulf/blob/development/.github/workflows/releasebuild.yml
# Thanks!

name: releasebuild

on:
  release:
    types:
      - published

jobs:
  distbuild:
    name: Checkout code and build tgz
    runs-on: ubuntu-latest
    steps:
      - name: Set the version
        id: version_number
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set the git source location
        id: source_loc
        run: |
          echo "SRC=${GITHUB_REF}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build tar.gz
        run: make dist

      - name: Upload mock script
        uses: actions/upload-artifact@v3
        with:
          name: mockbuild.sh
          path: ci/mockbuild.sh

      - name: Upload tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: xl-${{ env.VERSION }}.tar.gz
          path: xl-${{ env.VERSION }}.tar.gz

  rpmbuild:
      name: Build using Rocky Linux
      needs: distbuild
      runs-on: ubuntu-latest
      container:
        image: rockylinux/rockylinux
        options: --privileged
      steps:
        - name: Set the version
          id: version_number
          run: |
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

        - name: Download mock build script
          uses: actions/download-artifact@v3
          with:
            name: mockbuild.sh

        - name: Download tar.gz
          uses: actions/download-artifact@v3
          with:
            name: xl-${{ env.VERSION }}.tar.gz

        - name: Set execute bit
          run: chmod +x mockbuild.sh

        - name: Run rpm build script
          run: ./mockbuild.sh  ${{ env.VERSION }}

        - name: See what the results are
          run: ls -lR

        - name: move rpms to main dir
          run: mv outputs/*.rpm .

        - name: Upload RPMs
          uses: actions/upload-artifact@v3
          with:
            name: xl-${{ env.VERSION }}-${{ env.RELEASE }}.el8
            path: xl-${{ env.VERSION }}-${{ env.RELEASE }}.el8.*.rpm

        - name: Upload Assets To Release
          if: "!github.event.release.prerelease"
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: "xl-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm"
            draft: false
            update_latest_release: true
            tags: true

        - name: Upload Assets To Pre-Release
          if: "github.event.release.prerelease"
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: "*.rpm"
            draft: false
            update_latest_release: false
            prerelease: true
            tags: true
            
